name: Deploy to Production

on:
  push:
    branches: [ prod ]

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} << 'SSHEOF'
          cd ${{ secrets.SERVER_PATH }}
          git fetch origin
          git reset --hard origin/prod
          chmod +x deploy-prod.sh
          ./deploy-prod.sh
        SSHEOF

    - name: Verify deployment
      run: |
        sleep 30
        curl -f https://api.inseat.achievengine.com/health || exit 1
        echo "✅ Production deployment successful!"
